apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "jenkins.dev/v1alpha1",
          "kind": "Jenkins",
          "metadata": {
            "name": "example-jenkins"
          },
          "spec": {
            "size": 3
          }
        }
      ]
    capabilities: Basic Install
  name: openshift-jenkins-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Placeholder description
  displayName: Openshift Jenkins Operator
  install:
    spec:
      deployments:
      - name: openshift-jenkins-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: openshift-jenkins-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: openshift-jenkins-operator
            spec:
              containers:
              - command:
                - openshift-jenkins-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: openshift-jenkins-operator
                image: quay.io/redhat-developer/openshift-jenkins-operator:latest
                imagePullPolicy: Always
                name: openshift-jenkins-operator
                resources: {}
              serviceAccountName: openshift-jenkins-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - openshift-jenkins-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - jenkins.dev
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: openshift-jenkins-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.0.1
