apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jenkinsimages.jenkins.dev
spec:
  group: jenkins.dev
  names:
    kind: JenkinsImage
    listKind: JenkinsImageList
    plural: jenkinsimages
    singular: jenkinsimage
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: JenkinsImage is the Schema for the jenkinsimages API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: JenkinsImageSpec defines the desired state of JenkinsImage
          properties:
            plugins:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                description: 'EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
                  NOTE: json tags are required.  Any new fields you add must have
                  json tags for the fields to be serialized. Defines Jenkins Plugin
                  structure'
                properties:
                  name:
                    type: string
                  version:
                    type: string
                required:
                - name
                type: object
              type: array
          required:
          - plugins
          type: object
        status:
          description: JenkinsImageStatus defines the observed state of JenkinsImage
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
